import {env} from 'cloudflare:workers';
import {initialState,type CareState} from './care-data';
import {CareError} from './care-errors';
export {CareError} from './care-errors';
function db():D1Database{if(!env.DB)throw new CareError('记录服务暂时不可用，请稍后重试。',503);return env.DB as D1Database;}
export function sessionId(request:Request){const raw=/(?:^|;\s*)care_sid=([^;]+)/.exec(request.headers.get('cookie')||'')?.[1];return raw&&/^[a-f\d-]{36}$/.test(raw)?raw:crypto.randomUUID();}
function normalize(raw:Partial<CareState>,revision:number):CareState{const base=initialState();return {...base,...raw,profile:{...base.profile,...raw.profile,companion:{...base.profile.companion,...raw.profile?.companion}},joined:Array.isArray(raw.joined)?raw.joined:base.joined,joinedGroups:Array.isArray(raw.joinedGroups)?raw.joinedGroups:base.joinedGroups,messages:Array.isArray(raw.messages)?raw.messages:base.messages,checkins:Array.isArray(raw.checkins)?raw.checkins:base.checkins,notifications:Array.isArray(raw.notifications)?raw.notifications:base.notifications,requests:Array.isArray(raw.requests)?raw.requests.map(item=>({...item,status:item.status==='completed'&&!item.resolvedAt?'awaiting_confirmation':item.status})):base.requests,revision};}
export async function readState(id:string):Promise<CareState>{const database=db();let row=await database.prepare('SELECT data,revision FROM care_sessions WHERE id = ?').bind(id).first<{data:string;revision:number}>();if(!row){await database.prepare('INSERT OR IGNORE INTO care_sessions (id,data,revision) VALUES (?, ?, 0)').bind(id,JSON.stringify(initialState())).run();row=await database.prepare('SELECT data,revision FROM care_sessions WHERE id = ?').bind(id).first<{data:string;revision:number}>();}if(!row)throw new CareError('记录没有加载成功，请重试。',503);return normalize(JSON.parse(row.data),row.revision);}
export async function writeState(id:string,state:CareState,revision:number){const next={...state,revision:revision+1};const result=await db().prepare('UPDATE care_sessions SET data = ?, revision = revision + 1 WHERE id = ? AND revision = ?').bind(JSON.stringify(next),id,revision).run();if(!result.meta.changes)throw new CareError('记录刚刚发生了变化，请刷新后再操作。',409);return next;}
export function reply(request:Request,id:string,data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','Set-Cookie':`care_sid=${id}; Path=/; HttpOnly; SameSite=Strict; Max-Age=31536000${new URL(request.url).protocol==='https:'?'; Secure':''}`}});}
export function failure(error:unknown){console.error('Care request failed:',error);return Response.json({error:error instanceof CareError?error.message:'暂时没能保存，请稍后重试。'},{status:error instanceof CareError?error.status:503,headers:{'Cache-Control':'no-store'}});}
