'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {Camera,Clock3,HeartHandshake,Mic,Phone,ShieldCheck,X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {HELP_TYPES,type HelpRequest,type HelpType,type MediaRef,type Role} from '@/lib/care-data';
import {clearLocalMedia} from '@/lib/local-media';
import {LocalAttachment,MediaComposer} from './care-media';

export type Mutate=(action:string,body?:Record<string,unknown>,success?:string)=>Promise<boolean>;
type Contact={name:string;phone:string};type Contacts={primary:Contact;backup:Contact};
const EMPTY:Contacts={primary:{name:'',phone:''},backup:{name:'',phone:''}};
const CONTACT_KEY='care-local-contacts-v2';const DRAFT_KEY='care-help-draft-v2';
const NAMES:Record<Role,string>={elder:'老人端',family:'家人端',volunteer:'义工端'};
const STATUS:Record<string,string>={pending_family:'还没有人接下',family_accepted:'家人已接下',family_declined:'家人暂时没空',family_forwarded:'等待义工接下（模拟）',volunteer_accepted:'义工已接下（模拟）',arranged:'已记下安排',awaiting_confirmation:'请老人确认是否解决',completed:'老人已确认解决',not_resolved:'还没解决，继续跟进',cancelled:'已撤销'};
export const ACTIONS:Record<string,string>={'family-view':'我看到了','family-accept':'我来处理','family-decline':'暂时没空','family-forward':'核对风险并模拟转派','volunteer-accept':'接下示例任务','arrange-help':'记下安排','complete-help':'处理完了，请老人确认','confirm-help':'确认已经解决','not-resolved':'还没解决','cancel-help':'撤销求助','reply-help':'说句话回应'};
function clock(value:string){return new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});}
function readContacts():Contacts{try{const raw=JSON.parse(localStorage.getItem(CONTACT_KEY)||'null');if(!raw)return EMPTY;const clean=(x:Contact):Contact=>({name:typeof x?.name==='string'?x.name.slice(0,20):'',phone:typeof x?.phone==='string'&&/^\+?\d{5,20}$/.test(x.phone)?x.phone:''});return {primary:clean(raw.primary),backup:clean(raw.backup)};}catch{return EMPTY;}}
function useContacts(){const [value,setValue]=useState<Contacts>(EMPTY);useEffect(()=>{const sync=()=>setValue(readContacts());sync();window.addEventListener('care-contact-change',sync);window.addEventListener('storage',sync);return()=>{window.removeEventListener('care-contact-change',sync);window.removeEventListener('storage',sync);};},[]);return value;}
function saveContacts(value:Contacts){localStorage.setItem(CONTACT_KEY,JSON.stringify(value));window.dispatchEvent(new Event('care-contact-change'));}

export function ContactPanel({onConfigure}:{onConfigure:()=>void}){
  const contacts=useContacts();const [call,setCall]=useState<Contact|null>(null);const [message,setMessage]=useState('');const p=contacts.primary;
  return <><section className="contact-hero"><div className="contact-hero-heading"><span className="contact-avatar"><HeartHandshake size={29}/></span><div><span className="eyebrow">需要时，先联系熟悉的人</span><h2>{p.name||'还没有设置家人电话'}</h2><p>{p.phone?'仅此设备预存电话，未绑定应用账号':'请家人帮助设置并核对号码'}</p></div></div><button className="btn btn-primary btn-wide call-primary" onClick={()=>p.phone?setCall(p):onConfigure()}><Phone size={26}/>{p.phone?`给${p.name||'家人'}打电话`:'设置家人电话'}</button><div className="backup-row"><button className="btn btn-secondary" onClick={()=>contacts.backup.phone?setCall(contacts.backup):onConfigure()}>{contacts.backup.phone?`联系${contacts.backup.name||'备用家人'}`:'设置备用联系人'}</button><button className="btn btn-secondary" onClick={onConfigure}>核对或修改</button></div></section><Dialog open={!!call} onOpenChange={open=>{if(!open){setCall(null);setMessage('');}}}><DialogContent className="care-dialog" showCloseButton={false}><DialogTitle>给{call?.name||'家人'}打电话</DialogTitle><DialogDescription>请核对号码。手机会处理拨号，打开拨号不代表接通，也不会自动结束求助。</DialogDescription><p className="phone-number">{call?.phone}</p><a className="btn btn-primary btn-wide" href={`tel:${call?.phone||''}`}>打开手机拨号</a><button className="btn btn-secondary" onClick={async()=>{try{await navigator.clipboard.writeText(call?.phone||'');setMessage('号码已复制，请用手机电话拨打。');}catch{setMessage('无法复制，请记下上面的号码。');}}}>复制号码</button>{message&&<p role="status">{message}</p>}<p className="section-help">桌面电脑或部分内置浏览器可能无法拨号。此功能不保证有人接听，不是紧急救援服务。</p><button className="btn btn-secondary" onClick={()=>setCall(null)}>关闭</button></DialogContent></Dialog></>;
}

export function ContactSettings(){
  const [value,setValue]=useState<Contacts>(EMPTY);const [message,setMessage]=useState('');const [clear,setClear]=useState(false);
  useEffect(()=>{setValue(readContacts());},[]);
  function submit(e:FormEvent){e.preventDefault();try{const next:Contacts={primary:{name:value.primary.name.trim(),phone:value.primary.phone.replace(/[\s-]/g,'')},backup:{name:value.backup.name.trim(),phone:value.backup.phone.replace(/[\s-]/g,'')}};for(const c of [next.primary,next.backup])if((c.name&&!c.phone)||(!c.name&&c.phone)||(c.phone&&!/^\+?\d{5,20}$/.test(c.phone)))throw new Error('称呼和电话请一起填写并核对；备用联系人可以都留空。');saveContacts(next);setMessage('本机电话已保存，请与本人核对。不会自动拨号或绑定账号。');}catch(e){setMessage(e instanceof Error?e.message:'没有保存，请重试。');}}
  return <section className="settings-card" id="contact-editor"><h2>家人协助设置电话</h2><form className="care-form" onSubmit={submit}>{(['primary','backup'] as const).map(key=><fieldset key={key}><legend>{key==='primary'?'首选联系人':'备用联系人（可不填）'}</legend><label>称呼<input maxLength={20} value={value[key].name} placeholder="例如：女儿" onChange={e=>setValue({...value,[key]:{...value[key],name:e.target.value}})}/></label><label>电话号码<input type="tel" maxLength={24} value={value[key].phone} placeholder="请填写并核对号码" onChange={e=>setValue({...value,[key]:{...value[key],phone:e.target.value}})}/></label></fieldset>)}<p className="section-help">号码仅保存到此浏览器，不上传，也不读取通讯录。请在老人知情的情况下配置。</p><button className="btn btn-primary">保存电话</button>{message&&<p role="status">{message}</p>}</form>{clear?<div className="care-form"><p>确认清除本机预存号码？之后需重新配置才能使用首页拨号入口。</p><button className="btn btn-danger" onClick={()=>{try{saveContacts(EMPTY);setValue(EMPTY);setClear(false);setMessage('本机号码已清除。');}catch{setMessage('没有清除成功，请检查浏览器存储。');}}}>确认清除号码</button><button className="btn btn-secondary" onClick={()=>setClear(false)}>保留号码</button></div>:<button className="btn btn-secondary" onClick={()=>setClear(true)}>清除本机预存号码</button>}</section>;
}

export function QuickHelp({onOpen}:{onOpen:(type:HelpType)=>void}){return <div className="quick-help"><button className="voice-primary" onClick={()=>onOpen('想找人聊聊')}><Mic size={34}/><strong>说话求助</strong><span>不用打字，说完再保存</span></button><button className="photo-primary" onClick={()=>onOpen('帮我看看')}><Camera size={34}/><strong>拍照求助</strong><span>通知、物品，拍给家人看</span></button></div>;}

export function EnhancedRequest({item,role,pending,onAsk,onContact}:{item:HelpRequest;role:Role;pending:boolean;onAsk:(action:string)=>void;onContact:()=>void}){
  const closed=['completed','cancelled'].includes(item.status);const ready=['pending_family','family_declined','not_resolved'].includes(item.status);
  const button=(action:string,primary=false)=><button key={action} className={`btn ${primary?'btn-primary':'btn-secondary'}`} disabled={pending} onClick={()=>onAsk(action)}>{ACTIONS[action]}</button>;
  return <article className="request-card enhanced-request"><div className="request-main"><div className="request-title-row"><div><span className="eyebrow">{item.createdByName} · {clock(item.createdAt)}</span><h3>{item.title}</h3></div><span className={`status-pill ${item.status==='not_resolved'?'status-alert':closed?'status-done':'status-waiting'}`}>{item.status==='pending_family'&&item.familyViewedAt?'家人已查看，还没有接下':STATUS[item.status]}</span></div><p>{item.description}</p><div className="attachment-list">{item.media?.map(m=><LocalAttachment key={m.id} item={m}/>)}</div><p className={`risk-text risk-${item.risk}`}>{item.risk==='high'?'付费、远途或敏感事项，不转派':item.risk==='medium'?'先请家人核对':'日常任务，家人仍需确认'}</p>{item.schedule&&<p className="arrangement"><Clock3 size={20}/>安排：{item.schedule}</p>}{item.familyMessage&&<div className="response-note"><HeartHandshake size={21}/><span>家人演示回应：{item.familyMessage}</span></div>}{item.volunteerName&&<p className="section-help">{item.volunteerName}</p>}{item.replies?.map(r=><div className="reply-bubble" key={r.id}><strong>{NAMES[r.role]} · 演示回复</strong>{r.text&&<p>{r.text}</p>}{r.media.map(m=><LocalAttachment key={m.id} item={m}/>)}<small>{clock(r.time)}</small></div>)}{role==='elder'&&ready&&<div className="unanswered"><p>尚未有人接下。演示不会自动通知家人，也不会自动找陌生人。</p><button className="btn btn-secondary" onClick={onContact}><Phone size={20}/>联系家人或查看备用电话</button></div>}<div className="request-actions">
    {role==='family'&&ready&&<>{!item.familyViewedAt&&button('family-view')}{button('family-accept',true)}{item.status!=='family_declined'&&button('family-decline')}</>}
    {role==='family'&&['family_accepted','family_declined','not_resolved'].includes(item.status)&&item.risk!=='high'&&button('family-forward')}
    {role==='family'&&item.status==='family_accepted'&&<>{button('arrange-help')}{button('complete-help',true)}</>}{role==='family'&&['volunteer_accepted','arranged'].includes(item.status)&&button('complete-help',true)}
    {role==='volunteer'&&item.status==='family_forwarded'&&button('volunteer-accept',true)}{role==='volunteer'&&item.volunteerName&&item.status==='volunteer_accepted'&&<>{button('arrange-help')}{button('complete-help',true)}</>}{role==='volunteer'&&item.volunteerName&&item.status==='arranged'&&button('complete-help',true)}
    {role==='elder'&&item.status==='awaiting_confirmation'&&<>{button('confirm-help',true)}{button('not-resolved')}</>}{role==='elder'&&item.status==='arranged'&&button('not-resolved')}{!closed&&(role!=='volunteer'||!!item.volunteerName)&&button('reply-help')}{role==='elder'&&!closed&&item.status!=='awaiting_confirmation'&&button('cancel-help')}
    </div>{item.status==='awaiting_confirmation'&&<p className="section-help">仍未结束，等待老人确认解决或反馈还没解决。</p>}</div></article>;
}

type Draft={clientId:string;type:HelpType;title:string;description:string;schedule:string;payment:string;distant:string;media:MediaRef[]};
function emptyDraft(type:HelpType):Draft{return {clientId:crypto.randomUUID(),type,title:type,description:'',schedule:'',payment:'unknown',distant:'unknown',media:[]};}
export type EnhancementModal={kind:'create';type:HelpType}|{kind:'confirm';title:string;description:string;action:string;requestId:string;primary:string};
export function EnhancementDialog({modal,role,pending,error,mutate,onClose,onDone}:{modal:EnhancementModal;role:Role;pending:boolean;error:string;mutate:Mutate;onClose:()=>void;onDone:()=>void}){
  return <Dialog open onOpenChange={open=>{if(!open&&!pending)onClose();}}><DialogContent className="care-dialog" showCloseButton={false} onInteractOutside={e=>e.preventDefault()}><button className="dialog-close btn btn-secondary" disabled={pending} aria-label="关闭，保留草稿" onClick={onClose}><X size={20}/>关闭</button><DialogTitle>{modal.kind==='create'?'把需要说给家人听':modal.title}</DialogTitle><DialogDescription>仅保存演示记录，未通知真实家人或义工。附件只保存在当前浏览器。</DialogDescription>{modal.kind==='create'?<CreateForm type={modal.type} mutate={mutate} pending={pending} error={error} onDone={onDone}/>:<ActionForm key={`${modal.requestId}-${modal.action}`} modal={modal} role={role} mutate={mutate} pending={pending} error={error} onDone={onDone}/>}</DialogContent></Dialog>;
}
function CreateForm({type,mutate,pending,error,onDone}:{type:HelpType;mutate:Mutate;pending:boolean;error:string;onDone:()=>void}){
  const [value,setValue]=useState(()=>emptyDraft(type));const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [saved,setSaved]=useState(false);
  useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(d&&HELP_TYPES.includes(d.type)&&typeof d.clientId==='string'&&typeof d.description==='string'&&Array.isArray(d.media))setValue({...emptyDraft(d.type),...d});}catch{}setReady(true);},[]);
  useEffect(()=>{if(!ready)return;try{localStorage.setItem(DRAFT_KEY,JSON.stringify(value));setSaved(true);}catch{setSaved(false);}},[ready,value]);
  async function submit(e:FormEvent){e.preventDefault();if(busy||pending)return;setMessage('');if(!value.description.trim()&&!value.media.length){setMessage('先说句话、加张照片或写几个字，不需要都填写。');return;}if(await mutate('create-help',value,'已保存演示求助，未通知真实家人')){try{localStorage.removeItem(DRAFT_KEY);}catch{}onDone();}}
  return <form className="care-form" onSubmit={submit}><p className="draft-state" role="status">{saved?'本机草稿已保留；尚未发送给真实家人。':'本机草稿暂未保存，请不要关闭页面。'}</p><MediaComposer value={value.media} onChange={media=>setValue(v=>({...v,media}))} onBusyChange={setBusy} disabled={pending}/><details><summary>选一种需要，或补充文字（可不填）</summary><div className="create-type-grid">{HELP_TYPES.map(t=><button className={`create-type ${value.type===t?'selected':''}`} type="button" key={t} aria-pressed={value.type===t} disabled={pending} onClick={()=>setValue({...value,type:t,title:t})}>{t}</button>)}</div><label>标题<input disabled={pending} maxLength={80} value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label>补充文字<textarea disabled={pending} rows={3} maxLength={240} value={value.description} onChange={e=>setValue({...value,description:e.target.value})} placeholder="可以只录音。文字可用手机已有的手写、五笔或拼音输入。"/></label><label>希望什么时候？（可不填）<input disabled={pending} maxLength={80} value={value.schedule} onChange={e=>setValue({...value,schedule:e.target.value})}/></label></details><div className="plain-risk"><h3>不确定也没关系，家人会再核对</h3>{([['payment','需要付钱吗？'],['distant','需要去很远的地方吗？']] as const).map(([key,title])=><fieldset key={key}><legend>{title}</legend><div className="risk-options">{[['unknown','不确定'],['no','不用'],['yes','需要']].map(([id,label])=><label key={id}><input type="radio" name={key} checked={value[key]===id} disabled={pending} onChange={()=>setValue({...value,[key]:id})}/>{label}</label>)}</div></fieldset>)}</div>{(message||error)&&<p className="inline-error" role="alert">{message||error}</p>}<button className="btn btn-primary btn-wide" type="submit" disabled={pending||busy||!ready}>{pending?'正在保存…':busy?'先说完并保存附件':'保存演示求助（不通知家人）'}</button></form>;
}
function ActionForm({modal,role,mutate,pending,error,onDone}:{modal:Extract<EnhancementModal,{kind:'confirm'}>;role:Role;mutate:Mutate;pending:boolean;error:string;onDone:()=>void}){
  const [text,setText]=useState('');const [media,setMedia]=useState<MediaRef[]>([]);const [clientId,setClientId]=useState(()=>crypto.randomUUID());const [busy,setBusy]=useState(false);const [checked,setChecked]=useState(false);const [schedule,setSchedule]=useState('');const [message,setMessage]=useState('');const [ready,setReady]=useState(false);
  const key=`care-reply-draft-${modal.requestId}-${role}`;const action=modal.action;
  useEffect(()=>{if(action==='reply-help')try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d){setText(typeof d.text==='string'?d.text:'');setMedia(Array.isArray(d.media)?d.media:[]);if(typeof d.clientId==='string')setClientId(d.clientId);}}catch{}setReady(true);},[action,key]);
  useEffect(()=>{if(action==='reply-help'&&ready)try{localStorage.setItem(key,JSON.stringify({text,media,clientId}));}catch{}},[action,key,ready,text,media,clientId]);
  async function submit(e:FormEvent){e.preventDefault();if(busy||pending)return;setMessage('');if(action==='reply-help'&&!text.trim()&&!media.length){setMessage('先说句话或写一句回复。');return;}if(action==='family-forward'&&!checked){setMessage('先核对任务内容和风险，再确认。');return;}
    if(await mutate(action,{requestId:modal.requestId,text,media,clientId,schedule,riskChecked:checked},'演示状态已保存，未通知真实用户')){if(action==='reset'){try{await clearLocalMedia();localStorage.removeItem(DRAFT_KEY);for(let i=localStorage.length-1;i>=0;i--){const k=localStorage.key(i);if(k?.startsWith('care-reply-draft-'))localStorage.removeItem(k);}}catch{setMessage('演示记录已重置，但本机附件未清除，请重试或清除本站浏览器数据。');return;}}if(action==='reply-help')try{localStorage.removeItem(key);}catch{}onDone();}
  }
  return <form className="care-form" onSubmit={submit}>
    {action==='reply-help'&&<><MediaComposer value={media} onChange={setMedia} onBusyChange={setBusy} photos={false} disabled={pending}/><label>也可以写一句话（可不填）<textarea rows={3} maxLength={240} value={text} disabled={pending} onChange={e=>setText(e.target.value)}/></label></>}
    {action==='arrange-help'&&<label>约定时间和地点<input required maxLength={80} disabled={pending} value={schedule} onChange={e=>setSchedule(e.target.value)} placeholder="例如：明天下午，在社区活动室"/></label>}
    {action==='family-forward'&&<><p>请核对是否涉及付费、远途、敏感资料或不适合义工处理的事项。不只看风险标签。</p><label className="consent-check"><input type="checkbox" checked={checked} disabled={pending} onChange={e=>setChecked(e.target.checked)}/>我已核对，确认可在演示中转派</label></>}
    {action==='complete-help'&&<p>仍留在进行中，不能替老人确认已经解决。</p>}{action==='confirm-help'&&<p>确实解决了再确认；否则返回选择“还没解决”。</p>}{action==='not-resolved'&&<p>重新进入跟进列表，原照片、语音和回复保留。</p>}{action==='family-decline'&&<p>求助不会结束。之后可以重新接下，或核对风险后模拟转派。</p>}{action==='family-view'&&<p>只记录已查看，不代表接下任务。</p>}{action==='cancel-help'&&<p>撤销演示求助后进入记录，未实际派出人员。</p>}{action==='reset'&&<p>清空演示求助、活动、文字卡、本机照片、录音及草稿，无法恢复。预存电话保留，可在联系人页面单独清除。</p>}
    {(message||error)&&<p className="inline-error" role="alert">{message||error}</p>}<button className={`btn ${action==='reset'?'btn-danger':'btn-primary'} btn-wide`} disabled={pending||busy||!ready}>{pending?'正在保存…':busy?'先说完并保存语音':modal.primary}</button>
  </form>;
}
